# Generated by Django 5.2.7 on 2026-02-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_menuitem_offer_price_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
