# Generated by Django 6.0.2 on 2026-02-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0011_helpmessage_alter_carousel_id_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpMessage',
        ),
    ]
