# Generated by Django 6.0.2 on 2026-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0016_remove_chatmessage_is_read_chatmessage_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialitem',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
