# Generated by Django 5.2.7 on 2026-02-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='menu/')),
                ('category', models.CharField(choices=[('juice', 'Juice'), ('chai', 'Chai & Snacks'), ('fastfood', 'Fast Food')], max_length=20)),
            ],
        ),
    ]
