# Generated by Django 6.0.2 on 2026-02-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0005_cart_session_key_alter_carousel_id_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default='default_session', max_length=100),
            preserve_default=False,
        ),
    ]
