# Generated by Django 6.0.2 on 2026-02-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0005_specialitem'),
        ('menuapp', '0006_alter_cart_session_key'),
    ]

    operations = [
    ]
