# Generated by Django 6.0.2 on 2026-02-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0008_remove_cart_session_key_alter_specialitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
