# Generated by Django 6.0.2 on 2026-02-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0013_chatmessage_helpmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpMessage',
        ),
    ]
