# Generated by Django 6.0.2 on 2026-02-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0015_chatmessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
