# Generated by Django 6.0.2 on 2026-02-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0017_specialitem_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='table_qr/')),
            ],
        ),
    ]
